#!/bin/bash

source docker.conf
source ../../k8s/init.conf

docker build \
        --build-arg MONGO_PACKAGE=mongodb-enterprise \
        --network mongonet \
        --add-host opsmgr:${opsMgrIp} \
        --build-arg DOWNLOAD=$OPSMGR \
        --build-arg PACKAGE=$AGENTPACKAGE \
        --build-arg MONGO_VERSION=$MONGO_VERSION \
        --build-arg MONGO_REPO=repo.mongodb.com \
        -t $DOCKER_USERNAME/mongodb:node_$MONGO_VERSION .

