version: '2'

services:
  node:
    image: "tjluckenbach/mongodb:node_4.2.6"
    environment:
      - DOWNLOAD="https://downloads.mongodb.com/on-prem-mms/deb"
      - MMSPACKAGE="mongodb-mms_4.3.9.100.20200331T2242Z-1_x86_64.deb"
      - OPSMGR="http://opsmgr:8080/download/agent/automation"
      - AGENTPACKAGE="mongodb-mms-automation-agent-manager_10.12.2.6205-1_amd64.ubuntu1604.deb"
    #command:
    ulimits:
        memlock: -1
    ports:
      - "27017:27017"
    volumes:
      - ./data:/shareddata
    container_name: "node"
#    networks:
#        mongonet:
            

networks:
  mongonet:
    ipam:
        driver: default
        config:
        - subnet: "172.19.0.0/24"

