#!/bin/bash

source docker.conf

data="$(pwd)/data"

docker run \
        --init --name opsmgr -h opsmgr \
        -p 8080:8080 \
        -p 27016:27017 \
        --network mongonet \
        -v ${data}:/shareddata  \
        -itd $DOCKER_USERNAME/opsmgr
#       -itd $DOCKER_USERNAME/opsmgr:$OPSMGR_VERSION 
