#!/bin/bash

source docker_id

docker build \
            --build-arg MONGO_PACKAGE=mongodb-enterprise \
            --network mongonet \
            --build-arg MONGO_REPO=repo.mongodb.com \
            -t $DOCKER_USERNAME/mongodb:node_$MONGODB_VERSION .

