---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: opsmanager-oplog
  namespace: mongodb
spec:
  members: 3
  version: 4.4.4-ent # 4.2.12-ent
  type: ReplicaSet
  opsManager:
    configMapRef:
      name: opsmanager-oplog # Must match metadata.name in ConfigMap file
  credentials: mongodb-opsmanager-admin-key
  persistent: true
  podSpec:
    cpu: "0.33"
    # note: it's important to always specify memory otherwise wired tiger cache will be calculated incorrectly and
    # monitoring tools will report the size of Kubernetes node instead of the real size of the container
    memory: 300Mi # 1Gi
    persistence:
      single:
        storage: 1Gi # 2Gi
  security:
    certsSecretPrefix: mdb # provide custom x509 certificates (keys and certs)
    tls:
      enabled: true # false
      ca: ca-pem # provide a custom certificate authority (cert in a pem file)
      secretRef:
        prefix: mdb
        # name: mdb-opsmanger-oplog-cert
    authentication:
      enabled : true
      modes: ["SCRAM"]
  # additionalMongodConfig: # use for 4.4 OM
  #   net:
  #     ssl:
  #       mode: "allowSSL" # "preferTLS"
