---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: NAME
  namespace: mongodb
spec:
  members: 3
  version: VERSION
  type: ReplicaSet
  opsManager:
    configMapRef:
      name: NAME # Must match metadata.name in ConfigMap file
  credentials: mongodb-opsmanager-admin-key
  persistent: true
  podSpec:
    cpu: "CPU"
    # note: it's important to always specify memory otherwise wired tiger cache will be calculated incorrectly and
    # monitoring tools will report the size of Kubernetes node instead of the real size of the container
    memory: MEM # 2Gi
    persistence:
      single:
        storage: DISK # 2Gi
  security:
    certsSecretPrefix: mdb # provide custom x509 certificates (keys and certs)
    tls:
      # enabled: true # false # deprecated in 1.16
      ca: ca-pem # provide a custom certificate authority (cert in a pem file)
      secretRef:
        prefix: mdb # same as certsSecretPrefix (not needed)
        # name: mdb-my-replica-set-cert
    authentication:
      enabled : true # false
      modes: ["SCRAM"]
  # The default TLS mode is 'requireTLS' but it can be customized using the
  # the `additionalMongodConfig` structure. Please find more information here:
  # https://docs.mongodb.com/manual/reference/configuration-options/#net.ssl.mode
  # additionalMongodConfig:
  #   net:
  #     ssl:
  #       mode: "preferSSL" # "requireSSL" "preferSSL" "allowSSL"
