---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: NAME
  namespace: mongodb
spec:
  members: 3
  version: VERSION
  type: ReplicaSet
  opsManager:
    configMapRef:
      name: NAME # Must match metadata.name in ConfigMap file
  credentials: mongodb-opsmanager-admin-key
  persistent: true
  podSpec:
    # `podTemplate` allows to set custom fields in PodTemplateSpec for the
    # Database Pods.
    # For more information see:
    # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#podtemplatespec-v1-core
    podTemplate:
      spec:
        containers:
        - name: mongodb-enterprise-database
          # For more information about Pod and container resource management, see:
          # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: "CPU"
              memory: MEM 
    persistence:
      single:
        storage: DISK # 2Gi
  security:
    certsSecretPrefix: mdb # provide custom x509 certificates (keys and certs)
    tls:
      # enabled: true # false # deprecated in 1.16
      ca: ca-pem # provide a custom certificate authority (cert in a pem file)
      secretRef:
        prefix: mdb # same as certsSecretPrefix (not needed)
        # name: mdb-myreplicaset-cert
    authentication:
      enabled : true # false
      modes: ["SCRAM"]
  # The default TLS mode is 'requireTLS' but it can be customized using the
  # the `additionalMongodConfig` structure. Please find more information here:
  # https://docs.mongodb.com/manual/reference/configuration-options/#net.ssl.mode
  # additionalMongodConfig:
  #   net:
  #     ssl:
  #       mode: "preferSSL" # "requireSSL" "preferSSL" "allowSSL"
  additionalMongodConfig:
    operationProfiling:
      mode: "off" # "slowOp"
      slowOpThresholdMs: 100
