---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: NAME

spec:
  replicas: 1
  version: VERSION # 6.0.6 # 5.0.14 # 4.4.15
  #Demo   jvmParameters: ["-Xms2560m", "-Xmx2560m"] # 2.5M is a good size for a demo -- comment out for larger clusters in production
  adminCredentials: admin-user-credentials # Should match metadata.name in the Kubernetes secret for the admin user
  statefulSet:
    spec:
      template:
        metadata:
          annotations:
            key1: value1
        spec:
          containers:
            - name: mongodb-ops-manager
              resources:  # 3Gi a good size for a demo -- use 5Gi or more for larger clusters in production
                limits:
                  #Demo   cpu: "0.75"
                  #Prod   cpu: "3.0"
                  #Demo   memory: 3Gi
                  #Prod   memory: 8Gi
                requests:
                  #Demo   cpu: "0.75"
                  #Prod   cpu: "2.0"
                  #Demo   memory: 3Gi
                  #Prod   memory: 5Gi

  #TLS security: # enables TLS for Ops Manager allowing it to serve traffic over HTTPS
  #TLS   tls:
  #TLS     # enabled: true (on by default here)
  #TLS     ca: "NAME-ca" 
  #TLS     secretRef: # secret containing the TLS certificate signed by known or custom CA. The secret must have a key "server.pem"
  #TLS       name: "NAME-cert"

  externalConnectivity:
    #LB  type: LoadBalancer
    #NP  type: NodePort # good for mini-kube (or where loadbalancer is not implemented)
    #NP  port: 32443

  applicationDatabase:
    members: 3
    version: APPDBVER # 5.0.9-ent # 4.4.4-ent
    # persistent: true
    #TLS security:
    #TLS # certsSecretPrefix: <prefix>
    #TLS   tls:
    #TLS     enabled: true
    #TLS     ca: "NAME-ca" # needs to be mms-ca.crt
    #TLS     # secretRef:
    #TLS     # name: "NAME-appdb-certs"
    podSpec:
      # cpu: "0.25"
      # memory: 500Mi # 4Gi
      persistence:
        single:
          storage: DISK # 5Gi
      podTemplate:
        spec:
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: "CPU"
                  memory: MEM
                requests:
                  cpu: "CPU"
                  memory: MEM
            - name: mongodb-agent
              resources:
                limits:
                  cpu: "0.15"
                  memory: 100Mi
                requests:
                  cpu: "0.1"
                  memory: 75Mi
            - name: mongodb-agent-monitoring
              resources:
                limits:
                  cpu: "0.15"
                  memory: 100Mi
                requests:
                  cpu: "0.1"
                  memory: 75Mi

  configuration:
    mms.ignoreInitialUiSetup: "true"
    mms.adminEmailAddr:   MMSADMINEMAILADDR
    mms.fromEmailAddr:    MMSEMAIL
    mms.replyToEmailAddr: MMSEMAIL
    mms.mail.hostname: "MMSMAILHOSTNAME"
    mms.mail.username: "MMSMAILUSERNAME"
    mms.mail.password: "MMSMAILPASSWORD"
    mms.mail.port: "25"
    mms.mail.ssl: "false"
    mms.mail.transport: smtp
    mms.user.bypassInviteForExistingUsers: "true"
    mms.publicApi.whitelistEnabled: "false"
    automation.versions.source: remote # hybrid
    mongodb.release.autoDownload: "false" # stop downloads of binaries (unless you need to demo recovery)
    mongodb.release.autoDownload.enterprise: "true"
    mongodb.release.modulePreference: enterpriseRequired
    #TLS brs.queryable.pem: /opt/mongodb/mms/secrets/queryable-backup.pem # stored in a secret
    brs.queryable.expiration: "3600000"

  backup:
    enabled: true
    headDB:
      storage: "4Gi" # optional. Default storage is 30G
    members: 1 # Configures the number of backup daemons to create (default 1)
    #Demo   jvmParameters: ["-Xms1024m", "-Xmx1536m"] # 1M is a good size for a demo -- comment out for larger clusters in production
    opLogStores:
      - name: oplog
        mongodbResourceRef:
          name: NAME-oplog
        mongodbUserRef:
          name: NAME-oplog-DBUSER
    blockStores:
      - name: blockstore
        mongodbResourceRef:
          name: NAME-blockstore
        mongodbUserRef:
          name: NAME-blockstore-DBUSER
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: mongodb-backup-daemon
                resources: # ~2Gi is good size for a demo -- use 5Gi for larger clusters in production
                  limits:
                    #Demo   cpu: "0.5"
                    #Prod   cpu: "3.0"
                    #Demo   memory: 1.7Gi
                    #Prod   memory: 8Gi 
                  requests:
                    #Demo   cpu: "0.5"
                    #Prod   cpu: "2.0"
                    #Demo   memory: 1.7Gi
                    #Prod   memory: 5Gi
