---
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: NAME-ldap
spec:
  username: "USER"
  db: $external  # external auth
  mongodbResourceRef:
    name: "NAME" # The name of the MongoDB resource this user will be added to
  roles:
    - db: "admin"
      name: "clusterAdmin"
    - db: "admin"
      name: "userAdminAnyDatabase"
    - db: "admin"
      name: "readWriteAnyDatabase"
    - db: "admin"
      name: "dbAdminAnyDatabase"

