---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-replica-set
  namespace: mongodb
spec:
  members: 3
  version: 4.2.8-ent
  type: ReplicaSet
  project: my-replica-set
  #credentials: admin-public-api-key
  credentials: opsmanager-admin-key
  persistent: true
  podSpec:
    cpu: "0.5"
    # note: it's important to always specify memory otherwise wired tiger cache will be calculated incorrectly and
    # monitoring tools will report the size of Kubernetes node instead of the real size of the container
    memory: 400Mi
    storage: 2Gi
  security:
    tls:
      enabled: true # true
      # ca: ca-pem
    authentication:
      enabled : true # true
      modes: ["SCRAM"]

  connectivity:
    replicaSetHorizons:
      - "horizon-1": "ac2d6cf5adf8b4ac282c1d44e1d3b00c-1550054797.us-west-2.elb.amazonaws.com:27017"
      - "horizon-1": "a467afbe955e14c2db56e32345012721-1263480511.us-west-2.elb.amazonaws.com:27017"
      - "horizon-1": "a77ce229a41d944209a6917cbef7b53d-1621567810.us-west-2.elb.amazonaws.com:27017"
