---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-replica-set
  namespace: mongodb
spec:
  members: 3
  version: 4.2.6-ent
  type: ReplicaSet
  project: my-replica-set
  #credentials: admin-public-api-key
  credentials: opsmanager-admin-key
  persistent: true
  podSpec:
    cpu: "0.5"
    # note: it's important to always specify memory otherwise wired tiger cache will be calculated incorrectly and
    # monitoring tools will report the size of Kubernetes node instead of the real size of the container
    memory: 400Mi
    storage: 1Gi
  security:
    tls:
      enabled: true
      # ca: ca-pem
    authentication:
      enabled : false
      # modes: ["SCRAM"]

# replicaSetHorizons consists of a list of maps where each map represents a node within
# the replica set and maps names of DNS horizons to externally connectable DNS names.
# The length of the replicaSetHorizons list must be equal to the number of the members in the
# replica set and each member should have all of the same DNS horizon names specified.connectivity:
  # connectivity:
  #   replicaSetHorizons:
  #     - "nodeport": "ec2-54-149-94-44.us-west-2.compute.amazonaws.com:32726"
  #     - "nodeport": "ec2-44-234-87-59.us-west-2.compute.amazonaws.com:31531"
  #     - "nodeport": "ec2-54-218-93-54.us-west-2.compute.amazonaws.com:31516"

