---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-replica-set
  namespace: mongodb
spec:
  members: 3
  version: 4.2.6-ent
  type: ReplicaSet
  project: my-replica-set
  #credentials: admin-public-api-key
  credentials: opsmanager-admin-key
  persistent: true
  podSpec:
    cpu: "0.5"
    # note: it's important to always specify memory otherwise wired tiger cache will be calculated incorrectly and
    # monitoring tools will report the size of Kubernetes node instead of the real size of the container
    memory: 400Mi
    storage: 2Gi
  security:
    tls:
      enabled: true
      # ca: ca-pem
    authentication:
      enabled : true
      modes: ["SCRAM"]

# replica set and each member should have all of the same DNS horizon names specified:
