---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: opsmanager

spec:
  replicas: 1
  version: 4.2.15
  jvmParameters: ["-Xms2560m", "-Xmx2560m"] # only for demo mode
  adminCredentials: admin-user-credentials # Should match metadata.name in the Kubernetes secret for the admin user
  statefulSet:
    spec:
      template:
        metadata:
          annotations:
            key1: value1
        spec:
          containers:
            - name: mongodb-ops-manager
              resources:
                limits:
                  cpu: "2.0"
                  memory: 3G # only for demo mode - 5GB or more is best

  security: # enables TLS for Ops Manager allowing it to serve traffic over HTTPS
    tls:
      # secret containing the TLS certificate signed by known or custom CA. The secret must have a key "server.pem"
      # and value of .pem file containing private key and TLS certificate
      secretRef: 
        name: opsmanager-cert

  externalConnectivity:
    type: LoadBalancer
    #type: NodePort
    #port: 32080

  applicationDatabase:
    members: 3
    version: 4.2.8-ent
    persistent: true
    security:
      tls:
        enabled: true
        ca: "appdb-ca"
        secretRef:
          name: "appdb-certs" # Name of the Secret object
    podSpec:
      cpu: "0.5"
      memory: 400Mi
      storage: 1Gi
 
  configuration:
    mms.ignoreInitialUiSetup: "true"
    automation.versions.source: mongodb
    mms.adminEmailAddr: thomas.luckenbach@mongodb.com
    mms.fromEmailAddr: thomas.luckenbach@mongodb.com
    mms.mail.hostname: smtp-svc.mongodb.svc.cluster.local
    mms.mail.port: "25"
    mms.mail.ssl: "false"
    mms.mail.transport: smtp
    mms.replyToEmailAddr: thomas.luckenbach@mongodb.com
    mms.user.bypassInviteForExistingUsers: "true"
    mms.publicApi.whitelistEnabled: "false"

  backup:
    enabled: true
    jvmParameters: ["-Xms1024m", "-Xmx1024m"] 
    opLogStores:
      - name: oplog1
        mongodbResourceRef:
          name: ops-mgr-backup
    blockStores:
      - name: blockStore1
        mongodbResourceRef:
          name: ops-mgr-backup
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: mongodb-backup-daemon
                resources:
                  requests:
                    cpu: "0.5"
                    memory: 1.2Gi  
