---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-replica-set
  namespace: mongodb
spec:
  members: 3
  version: 4.2.6-ent
  type: ReplicaSet
  project: ops-mgr-config
  #credentials: admin-public-api-key
  credentials: opsmanager-admin-key
  persistent: true
  podSpec:
    cpu: "0.5"
    # note: it's important to always specify memory otherwise wired tiger cache will be calculated incorrectly and
    # monitoring tools will report the size of Kubernetes node instead of the real size of the container
    memory: 250Mi
    storage: 1Gi

#security:
#    tls:
#      enabled: true

#  connectivity:
    # replicaSetHorizons consists of a list of maps where each map represents a node within
    # the replica set and maps names of DNS horizons to externally connectable DNS names.
    # In the following example, this would allow a client to make a replica set connection
    # from outside the replica set using a connection string like
    # mongodb://mdb0-test-website.com:1337,mdb1-test-website.com:1338,mdb2-test-website.com:1339.
    # The length of the replicaSetHorizons list must be equal to the number of the members in the
    # replica set and each member should have all of the same DNS horizon names specified.connectivity:
#    replicaSetHorizons:
#      - "my-replica-set": "docker-desktop:32016"
#      - "my-replica-set": "docker-desktop:32242"
#      - "my-replica-set": "docker-desktop:31539"

