---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-replica-set
  namespace: mongodb
spec:
  members: 3
  version: 4.2.6-ent
  type: ReplicaSet
  project: my-replica-set
  #credentials: admin-public-api-key
  credentials: opsmanager-admin-key
  persistent: true
  podSpec:
    cpu: "0.5"
    # note: it's important to always specify memory otherwise wired tiger cache will be calculated incorrectly and
    # monitoring tools will report the size of Kubernetes node instead of the real size of the container
    memory: 400Mi
    storage: 1Gi
  security:
    tls:
      enabled: true
      # ca: ca-pem
    authentication:
      enabled : true
      modes: ["SCRAM"]

# replica set and each member should have all of the same DNS horizon names specified:
  # connectivity:
  #   replicaSetHorizons:
  #     - "nodeport": "ec2-54-71-34-20.us-west-2.compute.amazonaws.com:32362"
  #     - "nodeport": "ec2-35-160-8-36.us-west-2.compute.amazonaws.com:32367"
  #     - "nodeport": "ec2-44-234-85-130.us-west-2.compute.amazonaws.com:32138"
