---
apiVersion: v1
kind: Service
metadata:
  name: my-replica-set-0
spec:
  ports:
  - nodePort:
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    statefulset.kubernetes.io/pod-name: my-replica-set-0
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: my-replica-set-1
spec:
  ports:
  - nodePort:
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    statefulset.kubernetes.io/pod-name: my-replica-set-1
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: my-replica-set-2
spec:
  ports:
  - nodePort: 
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    statefulset.kubernetes.io/pod-name: my-replica-set-2
  type: NodePort
