---
apiVersion: v1
kind: Service
metadata:
  name: opsmanager-svc-ext
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: queryablebackup
    port: 25999
    protocol: TCP
    targetPort: 25999
  selector:
    statefulset.kubernetes.io/pod-name: opsmanager-0
  type: LoadBalancer
