---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: opsmanager-backup-daemon
    controller: mongodb-enterprise-operator
  name: opsmanager-backup-daemon-0
  namespace: mongodb
spec:
  clusterIP: None
  ports:
  - name: mongodb
    port: 8443
    protocol: TCP
    targetPort: 8443
  publishNotReadyAddresses: true
  selector:
    statefulset.kubernetes.io/pod-name: opsmanager-backup-daemon-0
    #app: opsmanager-backup-daemon-0
  sessionAffinity: None
  type: ClusterIP
