#!/bin/bash

export DOCKER_USERNAME=tjluckenbach
export MONGODB_VERSION=4.2

dataloc="/opt/mongo/OpsMgr/server/data"

docker run \
        --init \
        --network mongonet \
        --name server -h server -p 27018:27017 \
        --mount type=bind,source=${dataloc},target=/shareddata  \
        -itd --privileged $DOCKER_USERNAME/automation:$MONGODB_VERSION
