#!/bin/bash

source docker.conf

AGENTPACKAGE=$AGENTPACKAGE5
MONGO_VERSION=$MONGO_VERSION5

#export DOCKER_USERNAME=username
chmod 755 ./docker-entrypoint.sh
docker build \
        --build-arg MONGO_PACKAGE=mongodb-enterprise \
        --build-arg PACKAGE=$AGENTPACKAGE \
        --build-arg MONGO_VERSION=$MONGO_VERSION \
        --build-arg MONGO_REPO=repo.mongodb.com \
        -t $DOCKER_USERNAME/mongodb:${MONGO_VERSION}-ent .

#docker build --build-arg MONGO_PACKAGE=mongodb-enterprise --build-arg MONGO_REPO=repo.mongodb.com -t $DOCKER_USERNAME/mongo-enterprise:$MONGODB_VERSION .
