apiVersion: v1
kind: Pod
metadata:
  name: PROJECT-NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT-NAME-svc
spec:
  containers:
  - image: tjluckenbach/mongodb:5.0.14-ent
    imagePullPolicy: IfNotPresent
    name: mongodb
    resources:
      limits:
        cpu: "0.50"
        memory: "400Mi"
      requests:
        cpu: "0.33"
        memory: "400Mi"
    ports:
    - containerPort: 27017
    volumeMounts:
    - mountPath: /shareddata
      name: shareddata
    command: [ "docker-entrypoint.sh" ]
    # command: [ "sleep" ]
    # args: [ "infinity" ]
  volumes:
  - name: shareddata
    configMap:
      name: shareddata
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: PROJECT-NAME-svc
  name: PROJECT-NAME
  namespace: NAMESPACE
spec:
  clusterIP: None
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: PROJECT-NAME-svc
  sessionAffinity: None
  type: ClusterIP
