#!/bin/bash

source docker.conf

data="$(pwd)/data"

#if [[ $1 == "" || $1 > 6 ]]
#then 
#    echo Need server number - from 0 to 2
#    exit
#fi

n=${1:-0}
ports=(27017 27018 27019)

MONGO_VERSION=$MONGO_VERSION6
docker run \
        --init \
        --network mongonet \
        --name mongodb${n} -h mongodb${n} -p ${ports[$n]}:27017 \
        -e MONGO_INITDB_ROOT_USERNAME=dbAdmin \
	-e MONGO_INITDB_ROOT_PASSWORD=Mongodb1 \
        -v /opt/Source/OpsMgr/Docker/6.x_node/config:/etc/mongo -d \
        $DOCKER_USERNAME/mongodb:${MONGO_VERSION}-ent --config /etc/mongo/mongodb.conf
        #-v /opt/Source/OpsMgr/Docker/6.x_node/config:/etc/mongo -d \ #mongo:6.0.4-ent --config /etc/mongo/mongodb.conf

docker exec -it mongodb${n} /usr/bin/mongosh -u dbAdmin -p Mongodb1 --eval "rs.initiate()" 



