#!/bin/bash

source docker.conf

AGENTPACKAGE=$AGENTPACKAGE44
MONGO_VERSION=$MONGO_VERSION44

docker build \
        --build-arg MONGO_PACKAGE=mongodb-enterprise \
        --build-arg PACKAGE=$AGENTPACKAGE \
        --build-arg MONGO_VERSION=$MONGO_VERSION \
        --build-arg MONGO_REPO=repo.mongodb.com \
        -t $DOCKER_USERNAME/mongodb:$MONGO_VERSION-ent .

