#!/bin/bash

source docker.conf
source ../../k8s/init.conf

data="$(pwd)/data"

if [[ $1 == "" || $1 > 9 ]]
then 
    echo Need server number - from 1 to 6
    exit
fi

n=$1
ports=(27017 27018 27019 27020 27021 27022 27023 27024 27025 20726)

docker network ls|grep mongonet >/dev/null 2>&1
if [[ $? != 0 ]]
then
docker network create mongonet
fi

docker run \
        --init \
        --network mongonet \
        --add-host opsmanager-svc.mongodb.svc.cluster.local:${opsMgrIp} \
        --name mongodb${n} -h mongodb${n} -p ${ports[$n]}:27017 \
        --mount type=bind,source=${data},target=/shareddata  \
        -itd --privileged $DOCKER_USERNAME/mongodb:node_$MONGO_VERSION


