#!/bin/bash

#3.2 community

source docker.conf

AGENTPACKAGE="${AGENTPACKAGE42}"
MONGOVERSION="${MONGOVERION42}"

docker build \
        --build-arg MONGO_PACKAGE=mongodb-org \
        --build-arg PACKAGE=${AGENTPACKAGE42} \
        --build-arg MONGO_REPO=repo.mongodb.org \
        -t ${DOCKER_USERNAME}/mongodb:node_3.2 .
