apiVersion: v1
kind: Pod
metadata:
  name: NAME
  namespace: mongodb
  labels:
    app: NAME-svc
spec:
  containers:
  - image: tjluckenbach/mongodb:node_3.2
    imagePullPolicy: IfNotPresent
    name: mongodb
    resources:
      limits:
        cpu: "2"
        memory: "2000Mi"
      requests:
        cpu: "1"
        memory: "2000Mi"
    ports:
    - containerPort: 27017
    volumeMounts:
    - mountPath: /shareddata
      name: shareddata
    command: [ "docker-entrypoint.sh" ]
    # command: [ "sleep" ]
    # args: [ "infinity" ]
  volumes:
  - name: shareddata
    configMap:
      name: shareddata
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: NAME-svc
  name: NAME
  namespace: mongodb
spec:
  clusterIP: None
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: NAME-svc
  sessionAffinity: None
  type: ClusterIP
